#! /bin/sh

## /home/jaime/.config/bspwm/bspwmrc
## ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
## ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
## ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
## ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
## ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
## ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
## 86

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output HDMI1 --mode 1920x1080 --pos 1920x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off --right-of eDP1
fi

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP1 -d 1 2 3 4
bspc monitor HDMI1 -d 5 6 7 8

bspc config normal_frame_opacity 0.9
bspc config focused_frame_opacity 0.7

bspc config border_width           1
bspc config window_gap             8
bspc config top_padding            0

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config pointer_follows_focus  true
bspc config focus_follows_pointer  true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a kitty      desktop='^1' follow=on
# bspc rule -a firefox    desktop='^2' follow=on
# bspc rule -a Thunar     desktop='^3' follow=on
# bspc rule -a doublecmd  desktop='^3' follow=on
# bspc rule -a Code       desktop='^4' follow=on
# bspc rule -a obsidian   desktop='^5' follow=on

# bspc rule -a mplayer2 state=floating
# bspc rule -a Yad state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Friday, October 14, 2022 @ 10:22:28 PM
# Update colors to Dracula https://draculatheme.com/bspwm
# Border
bspc config focused_border_color        "#8be9fd"
# bspc config focused_border_color        "#ff79c6"
bspc config active_border_color         "#bd93f9"
# bspc config active_border_color         "#6272a4"
bspc config normal_border_color         "#44475a"
bspc config presel_feedback_color       "#6272a4"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
